# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

dist: "trusty"

install:
  - yarn install
  - pip3 install --user -r requirements.txt
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin 1.2.0
  - export GOPATH=$GOPATH:/home/travis/build/vmware/precaution/test/fixtures/go
language: node_js
node_js:
  - "8"
  - "10"
  - "11"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

notifications:
  disabled: true
